# Generated by Django 4.2.7 on 2023-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория получателей',
                'verbose_name_plural': 'категории получателей',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('category', models.ManyToManyField(to='recipients.category', verbose_name='категория получателя')),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'получатели',
            },
        ),
    ]
