# Generated by Django 4.2.7 on 2023-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата_создания')),
                ('slug', models.CharField(max_length=250, verbose_name='slug')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='дата_публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ('views_count', 'title', 'published_at'),
            },
        ),
    ]
